// Generated by https://quicktype.io

// Generated by https://quicktype.io
// Generated by https://quicktype.io
export interface IGameContext {
  gameState: GameState | undefined;
  newGame: () => Promise<void>;
  updateGame: (ev: KeyboardEvent) => Promise<void>;
  hiscore: number;
}
export interface ProcessGame {
  processGame: ProcessGameData;
}

export interface ProcessGameData extends GameState {
  __typename: string;
}

export interface NewGameResponse {
  newGame: NewGame;
}

export interface NewGame {
  __typename: string;
  state: Array<number[]>;
  score: number;
  finished: boolean;
}
export interface GameState {
  state: Array<number[]>;
  score: number;
  finished: boolean;
}
