// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface NewGameResponse {
  newGame: NewGame;
}

export interface NewGame {
  __typename: string;
  state: Array<number[]>;
  score: number;
  finished: boolean;
}
export interface GameState {
  state: Array<number[]>;
  score: number;
  finished: boolean;
}
