// Generated by https://quicktype.io

export interface AllScores {
    allScores: AllScore[];
}

export interface AllScore {
    __typename: AllScoreTypename;
    score:      number | null;
    player:     Player;
    id:         string;
}

export enum AllScoreTypename {
    Score = "Score",
}

export interface Player {
    __typename: PlayerTypename;
    id:         string;
    name:       string;
}

export enum PlayerTypename {
    User = "User",
}
