import { RegisterFormInput } from ".";

export interface IAuthContext {
  authUser: (
    inputData: Pick<RegisterFormInput, "email" | "password">
  ) => Promise<any>;
  loading: boolean;
  user: User | null;
  logout: () => void;
}
export interface User {
  token: string;
  username: string;
  userid: string;
}
// Generated by https://quicktype.io

export interface UserScores {
  allScores: AllScore[];
}

export interface AllScore {
  score: number;
  player: Player;
  __typename: string;
}

export interface Player {
  name: string;
  __typename: string;
}

// Generated by https://quicktype.io

export interface UserAuthData {
  authenticateUserWithPassword: AuthenticateUserWithPassword;
}

export interface AuthenticateUserWithPassword {
  token: string;
  item: Item;
  __typename: string;
}

export interface Item {
  id: string;
  name: string;
  __typename: string;
}
