"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { ApolloProvider } from "@apollo/client";
import { apolloClient } from "@/utils/Apollo";
import { CookiesProvider } from "react-cookie";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <CookiesProvider>
        <ApolloProvider client={apolloClient()}>
          <body className={inter.className}>{children}</body>
        </ApolloProvider>
      </CookiesProvider>
    </html>
  );
}
